title: Ohjelmointi 2
description: Haaga-Helia / Ohjelmointi 2 (SOF001AS3A)
theme: just-the-docs
repository: ohjelmointi2/ohjelmointi2.github.io
url: https://ohjelmointi2.github.io

aux_links:
  Opintojaksokuvaus: https://opinto-opas.haaga-helia.fi/course_unit/SOF001AS3A

permalink: /:title

plugins:
  - jekyll-target-blank

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  esim:
    title: Esimerkki
    color: green
  huom:
    title: 💡 Huomio!
    color: green
  vinkki:
    title: Vinkki
    color: green

gh_edit_link: true
gh_edit_link_text: "📝 Muokkaa sivua GitHubissa"
gh_edit_repository: "https://github.com/ohjelmointi2/ohjelmointi2.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"