title: Ohjelmointi 2
description: Haaga-Helia / Teemu Havulinna
github:
  is_project_page: false
google_analytics: UA-182579893-1
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme